services:
  ralloc:
    container_name: ralloc
    build:
      context: ../
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - ../apps/web/.env.production
      - ../apps/web/.env.local
      - ../apps/ws/.env.production
      - ../packages/core/.env.production
    restart: "no"
    environment:
      - FORCE_COLOR=1
    ports:
      - 3000:3000
    networks:
      - ralloc_net
    depends_on:
      redis:
        condition: service_healthy
    
  ralloc-ws:
    container_name: ralloc-ws
    build: 
      context: ../
      dockerfile: ./apps/ws/Dockerfile
    env_file:
      - ../packages/core/.env.production
      - ../apps/ws/.env.production
      - ../apps/web/.env.local
    environment:
      - NODE_ENV=production
    restart: "no"
    ports: 
      - 6767:6767
    networks:
      - ralloc_net
    depends_on:
      redis: 
        condition: service_healthy

  redis:
    image: redis:8-alpine
    container_name: ralloc-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - ./ralloc_redis_data:/data
      - ../redis.prod.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ralloc_net

networks:
  ralloc_net:
    external: true

volumes:
  ralloc_redis_data:
    driver: local
