services:
  ralloc:
    container_name: ralloc
    image: ghcr.io/tomasvana10/ralloc:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - ../apps/web/.env.production
      - ../apps/web/.env.local
      - ../apps/ws/.env.production
      - ../apps/.env.production
    restart: unless-stopped
    environment:
      - FORCE_COLOR=1
    ports:
      - 3000:3000
    networks:
      - ralloc_net
    depends_on:
      redis:
        condition: service_healthy
  
  ralloc-ws:
    container_name: ralloc-ws
    image: ghcr.io/tomasvana10/ralloc-ws:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - ../apps/.env.production
      - ../apps/ws/.env.production
      - ../apps/web/.env.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports: 
      - 6767:6767
    networks:
      - ralloc_net
    depends_on: 
      redis: 
        condition: service_healthy

  redis:
    image: redis:8-alpine
    container_name: ralloc-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./ralloc_redis_data:/data
      - ../redis.prod.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ralloc_net
  
  watchtower:
    image: containrrr/watchtower
    container_name: ralloc-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=true
    networks:
      - ralloc_net

networks:
  ralloc_net:
    external: true

volumes:
  ralloc_redis_data:
    driver: local
